services:
  postgres_db:
    image: postgres:15-alpine
    container_name: campus_postgres
    environment:
      POSTGRES_DB: campus_placement
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - campus_network

  backend:
    build: ./backend
    container_name: campus_backend
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_db:5432/campus_placement
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - JWT_SECRET=your_very_long_random_jwt_secret_key_here
      - HIBERNATE_DDL_AUTO=update
      - SHOW_SQL=true
    depends_on:
      - postgres_db
    networks:
      - campus_network

  frontend:
    build: ./frontend
    container_name: campus_frontend
    ports:
      - "80:80"
    environment:
      - VITE_API_BASE_URL=http://localhost:8081
    depends_on:
      - backend
    networks:
      - campus_network

networks:
  campus_network:
    driver: bridge

volumes:
  postgres_data:
